add <jbroot> environment variable
opa334/Dopamine pull request #43
Opened 2023-04-21 19:06 UTC by tuancc-repo

just a stub, and keep /var/jb compatible.

2023-04-22 14:17 UTC, tuancc-repo commented
Add support for jailbroken apps/tweaks to access files in /var/jb after hide-environment (temporarily remove /var/jb path symbols)

2023-04-28 13:02 UTC, mkwiimaster7 commented
I hope this gets added to Dopamine lol

2023-04-28 13:27 UTC, bakirfatah99 commented
Hello opa334 next update will add rootfull jailbreak?

I would appreciate it if you replied!

2023-05-04 18:10 UTC, Cryptiiiic requested changes

2023-05-04 18:10 UTC, Cryptiiiic commented on BaseBin/systemhook/src/main.c
> +		setenv("jbroot", jbroot, 0);
env vars are usually standardized as UPPERCASE so JBROOT

2023-05-13 16:52 UTC, closed without merging