Update Russian Traslation
opa334/Dopamine pull request #52
Opened 2023-04-23 14:48 UTC by armanism

2023-04-30 22:22 UTC, sourcelocation requested changes
![DB7F05FC-CA37-407D-AE55-8AB0A76C93AE](https://user-images.githubusercontent.com/52459150/235378675-3c96de0f-618f-4f46-8a46-622f4b4671ba.jpeg)
Спасибо за перевод - делал оригинал в спешке. Только можете вернуть этот перевод обратно?

2023-05-01 00:19 UTC, armanism commented
Приветствую, "mobile password" - так и не понял что это?
Пользовательский пароль телефона, или же пароль пользователя в для командной строки? Или все вместе?

2023-05-01 11:58 UTC, sourcelocation commented
Это пароль ssh, если простыми словами

2023-05-01 11:59 UTC, sourcelocation commented
то есть для коммандной строки

2023-05-01 12:38 UTC, armanism commented
Применяй, потом глянем. Если что откорректируем

2023-05-02 14:50 UTC, merged